dist: trusty
language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
# command to run tests
install: pip install requests
script: python3 -m unittest discover -v
